<script src="<?php echo $this->serverUrl().$this->baseUrl("scripts/js/jquery.js")?>" type="text/javascript"></script>
<!--<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>-->
<!--<script src="http://view.jqueryui.com/menu/ui/jquery.ui.menu.js"></script>-->
<!--<script src="<?php //echo $this->serverUrl().$this->baseUrl("scripts/js/jquery.collapsible-menus.js")?>" type="text/javascript"></script>-->


<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }

    
   ul li.level1 span {
      font-weight:  bold;
      color : #800000;
      cursor : pointer;
   }
 
   ul li.level1 ul li {
    font-weight : normal;
    color : black;
   }
 
   ul li.level1 ul {
      display : none;
   }
   
   .left
   {
       float: left;
   }
   
   .margin
   {
       margin-left: 20px;
       margin-right: 10px;
   }
   
   .menu
   {
       float: top;
   }
    
    
</style>

<!--    <li><a href="<?php
//           echo $this->url(
//                   array(
//               'controller' => 'user',
//               'action' => 'add'
//                   ), 'default', true)
?>" onmouseover="openelement('menu2')">Dodaj Użytkownika</a>-->

<!--the end of the HTML code for the menu -->

<!--<body style="font-size:62.5%;">-->
<div id="menu">
<ul>
		<li class="level1 left"><span>Opcja 1</span>
			<ul>
                        <li><a href="<?php
           echo $this->url(
                   array(
               'controller' => 'user',
               'action' => 'add'
                   ), 'default', true)
            ?>">Dodaj użytkownika</a></li>
				<li><a href="<?php
           echo $this->url(
                   array(
               'controller' => 'user',
               'action' => 'delete'
                   ), 'default', true)
            ?>">Usuń użytkownika</a></li>
				<li>opcja 1.3</li>
				<li>opcja 1.4</li>
				<li><a href="#">opcja 1.5</a></li>
			</ul>
		</li>
		<li class="level1 left margin"><span>Opcja 2</span>
			<ul>
				<li><a href="#">opcja 2.1</a></li>
				<li><a href="#">opcja 2.2</a></li>
				<li>opcja 2.3</li>
				<li>opcja 2.4</li>
			</ul>
                </li>
</ul>
</div>
                
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>

    <h3>This is your project's main page</h3>

    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>



<script type="text/javascript">
 
$(document).ready(
 function()
 {
    $("li.level1").children("span").click(function() {
       $("li.level1").not(this).children("ul:visible").hide("slow");
       if($(this).next("ul").css("display") == 'block')
          $(this).next("ul").hide("slow");
       else
          $(this).next("ul").show("slow");
    });
 });
</script>

    

