
<style>
#menu { 
text-align: left; 
overflow: hidden; 
font-family: calibri, tahoma; 
} 
 
ul#menu li { 
border: 1px solid #d5d5d5; 
list-style-type: none; 
float: left; 
background: #e9e9e9; 
margin-left: 3px; 
} 
 
ul#menu li:hover { 
border: 1px solid #d5d5d5; 
list-style-type: none; 
float: left; 
background: #f0f0f0; 
margin-left: 3px; 
} 
 
ul#menu li a { 
display : block; 
padding : 4pt; 
text-decoration : none; 
} 
 
ul#menu li li a { 
width: 160px; 
} 
 
ul#menu li li:hover { 
background: white; 
} 
 
ul#menu li ul { 
overflow: hidden; 
display: none; 
} 
 
ul#menu li:hover ul { 
position: absolute; 
background: #aaa; 
padding: 0; 
display: block; 
width: 160px; 
} 
   
</style>


<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>add</b></p>
</div>


<ul id="menu"> 
    <li><a href="" title="">Start</a></li> 
    <li><a href="" title="">Portfolio</a> 
    <ul>
    <li><a href="" title="">Portfolio</a>         
        <ul>
            <li><a href="#" title="">Strony www</a></li> 
        </ul>
    </ul> 
    </li> 
    <li><a href="" title="">Artykuły</a></li> 
    <li><a href="" title="">Informacje</a> 
    <ul> 
    <li><a href="" title="">O mnie</a></li> 
    <li><a href="" title="">Aktualności</a></li> 
    </ul> 
    </li> 
    <li><a href="" title="">Webdesign</a></li> 
    <li><a href="" title="">Kontakt</a> 
    <ul> 
    <li><a href="" title="">Formularz kontaktowy</a></li> 
    <li><a href="" title="">Pomoc</a></li> 
    </ul> 
    </li> 
    <li><a href="" title="">Współpraca</a> 
    <ul> 
    <li><a href="" title="">Wymiana linkiem</a></li> 
    </ul> 
    </li> 
</ul> 