<script src="<?php echo $this->serverUrl().$this->baseUrl("scripts/js/jquery.js")?>" type="text/javascript"></script>

<style type="text/css">
a {
	font:11px Arial, Helvetica, sans-serif;
	color:#fff;
	text-decoration:none;
	line-height:1.3em;
	display:block;
	background:#333;
	padding:7px 15px;
	margin:0 1px 0 0;
}
 
ul {
	list-style:none;
	margin:0;
	padding:0;
}

.menu-lvl-1 {}

.lvl-1 {
	position:relative;
	float:left;
}


.lvl-1:hover a {
	text-decoration:underline;
	color:#fff;
	background:#c11;
}

.menu-lvl-2 {
	position:absolute;
	width:150px;
	display:none;
	background:url(../);
}

.lvl-2 {
	position:relative;
	margin-top:1px;
}

.lvl-1:hover .lvl-2 a {
	color:#fff;
	text-decoration:none;
	background:#333;
}


.lvl-1:hover .lvl-2 a:hover {
	text-decoration:underline;
	color:#fff;
	background:#c11 ;
}

.lvl-1:hover .lvl-2:hover a {
	text-decoration:underline;
	color:#fff;
	background:#c11 ;
}


.menu-lvl-3 , .menu-lvl-4{
	position:absolute;
	left:100%;
	top:0;
	@top:3px;
	display:none;
}


.lvl-3 {
	margin-bottom:1px;
}

.lvl-1:hover .lvl-2:hover .lvl-3 a {
	text-decoration:none;
	color:#fff;
	background:#333;
}

.lvl-1:hover .lvl-2:hover .lvl-3 a:hover{
	text-decoration:underline;
	color:#fff;
	background:#c11;
}

/**/
.lvl-1:hover .lvl-2:hover .lvl-3:hover .lvl-4 a{
    text-decoration:none;
    color:#fff;
    background:#333;
}
 
.lvl-1:hover .lvl-2:hover .lvl-3:hover .lvl-4 a:hover {
    text-decoration:underline;
    color:#fff;
    background:#c11;
}

</style>
<noscript>
<style type="text/css">
.lvl-1:hover .menu-lvl-2 {
	display:block;
}
.lvl-2:hover .menu-lvl-3 {
	display:block;
}

.lvl-3:hover .menu-lvl-4 {
    display:block;
}

</style>
</noscript>

<!--http://www.webinside.com.pl/2010/11/wielopoziomowe-menu-htmlcssjs/-->

<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>delete</b></p>
</div>



<ul class="menu-lvl-1">
    <li class="lvl-1"><a href="" title="">Home</a></li>
    <li class="lvl-1">
        <a href="" title="">Oferta</a>
        <ul class="menu-lvl-2">
            <li class="lvl-2"><a href="" title="">Administracja stronami</a></li>
            <li class="lvl-2">
                <a href="" title="">Gotowe szablony </a>
               <ul class="menu-lvl-3">
                    <li class="lvl-3">
                        <a href="" title="">Jeszcze więcej Gotowych szablonów </a>                    
                    <ul class="menu-lvl-4">
                         <li class="lvl-4"><a href="" title="">Drupal 2</a></li>
                         <li class="lvl-4"><a href="" title="">Joomla 2</a></li>
                         <li class="lvl-4"><a href="" title="">WordPress 2</a></li>
                     </ul>
                    </li>
                    <li class="lvl-3"><a href="" title="">Drupal</a></li>
                    <li class="lvl-3"><a href="" title="">Joomla</a></li>
                    <li class="lvl-3"><a href="" title="">WordPress</a></li>
                </ul>
            </li>
            <li class="lvl-2"><a href="" title="">Projekty graficzne</a></li>
            <li class="lvl-2"><a href="" title="">Cięcie i kodowanie</a></li>
            <li class="lvl-2"><a href="" title="">Audyty stron www</a></li>
            <li class="lvl-2"><a href="" title="">Inne</a></li>
        </ul>
    </li>
    <li class="lvl-1"><a href="" title="">O nas</a></li>
    <li class="lvl-1"><a href="" title="">Realizacje</a></li>
    <li class="lvl-1"><a href="" title="">Kontakt</a></li>
</ul>

<script type="text/javascript">
$(function(){
	function showIt(liClass){
		$(liClass).hover(
			function() {
				$('ul',this).first().slideDown()
			},
			function() {
				$('ul',this).first().slideUp()
			}
		)
	}
	
	showIt('.lvl-1')
	showIt('.lvl-2')
	showIt('.lvl-3')        
})
</script>